### ISSUE TITLE
Remove Dependabot and introduce a semver respecting GH Action that generates a single PR only. 

### ISSUE THREAD

**Issue by georgiee** [satellytes/satellytes.com#508]
I would like to remove dependabot. It's a lot of noise, especially with the ungrouped behavior. It's working right now but onl because @feedm3 is doing the manual work of merging the PRs part by part on each Monday.

Increasing the cadence is no option as we only collect and postpone additional changes.

Let's go full circle and be back at the solution @feedm3 provided initially, maybe with some additional improvements because we cam to dependabot because of a very important things: I want the script to respect our semver ranges.

Locally we would use `yarn upgrade-interactive` to update within the ranges step by step. Occasionally we would run `yarn upgrade-interactive --latest` to look outside of the semver ranges for new major release we might like.

I'm sure it should be possible to run an update that respects semver instead of just pulling in any version, including beta versions. I don't want that, it feels super wrong. 

Here the [previous github action file](https://github.com/satellytes/satellytes.com/commit/b41170ddf5847cbf71c831604109af0ecd648034) I deleted instead of disabling it (as suggest by @fischeversenker afterwards, sorry for that 🙏)

Can we find a better workflow ? Thank you!

**Comment by feedm3** [comment]
One possible solution to prevent beta updates: Switch back to NPM and use `ncu` for the updates. It has more functionality than the native `yarn upgrade` and may (needs some research) also respect semver better.

https://www.npmjs.com/package/npm-check-updates

**Comment by georgiee** [comment]
There are some options for yarn upgrade, don't they help ? Like the `--caret` addition? But yes we could consider switching to `npm`

```
yarn upgrade --help

    -S, --scope <scope>                 upgrade packages under the specified scope
    -L, --latest                        list the latest version of packages, ignoring version ranges in package.json
    -E, --exact                         install exact version. Only used when --latest is specified.
    -P, --pattern [pattern]             upgrade packages that match pattern
    -T, --tilde                         install most recent release with the same minor version. Only used when --latest is specified.
    -C, --caret                         install most recent release with the same major version. Only used when --latest is specified.
    -A, --audit                         Run vulnerability audit on installed packages
    -h, --help                          output usage information
```

**Comment by milljoniaer** [comment]
Did I get this right, that we can just take the old github action and add an `-- caret` to the yarn command?


```yml
name: Scheduled Dependency Update

on:
  # run this workflow manually from the Actions tab
  workflow_dispatch:

  # every monday at 02:00
  schedule:
    - cron: '0 2 * * 1'

jobs:
  dependency-update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Upgrade dependencies
        run: yarn upgrade --latest --caret

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          branch: chore-dependency-update
          delete-branch: true
          title: "chore: dependency update 🧹"
          commit-message: "chore: dependency update"
          body: |
            This PR was automatically created.
            - All dependencies are updated to the latest version.
            - This PR will be created every monday at 2am and the branch will be force pushed.
            - If all checks are green, feel free to merge it. 
```
